services:
  - type: web
    name: ecocoleta-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npx prisma generate --schema=prisma/schema.prod.prisma && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: "7d"
      - key: CORS_ORIGIN
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
